on:
  push:
    branches:
      - src

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: "Deploy Nikola to GitHub Pages"
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Build and Deploy Nikola
        uses: getnikola/nikola-action@v8
        with:
          dry_run: false
